config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index]
  
  get 'comments/create'
  
  resources :blogs do
    resources :comments
  end
  
  root "blogs#index"

  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :followed, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
    has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :active_relationships, source: :follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
    @comments = @blog.comments
    @comment = @blog.comments.build
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog, only: [:create, :edit, :update]

  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.build(comment_params)

    respond_to do |f|
      if @comment.save
        f.js { render :index }
      else
        f.html { redirect_to blog_path(@blog), notice: "Couldn't Post..." }
      end
    end
  end

  def edit
    @comment = @blog.comments.find(params[:id])
    respond_to do |f|
      flash.now[:notice] = 'Comment Edit'
      f.js {render :edit}
    end
  end

  def update
    @comment = @blog.comments.find(params[:id])
    respond_to do |f|
      if @comment.update(comment_params)
        flash.now[:notice] = 'Comment Edited'
        f.js { render :index }
      else
        flash.now[:notice] = 'Comment Cannot be Edited'
        f.js { render :edit_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'Comment deleted'
      format.js { render :index }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:blog_id, :content)
  end

  def set_blog
    @blog = Blog.find(params[:blog_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="container">

  <p>
    <strong>Title:</strong>
    <%= @blog.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @blog.content %>
  </p>

  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
  </div>

  <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>

  <%= link_to 'Edit', edit_blog_path(@blog) %> |
  <%= link_to 'Back', blogs_path %>

</div>

app/views/comments/_edit.html.erb
<%= form_with(model: [blog, comment]) do |f| %>
    <% if comment.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(comment.errors.count, "error") %> found</h2>
            <ul>
                <% comment.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.text_area :content, id: "comment_content_#{blog.id}" %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [blog, comment]) do |f| %>
    <% if comment.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(comment.errors.count, "error") %> found</h2>
            <ul>
                <% comment.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
    <% comments.each do |comment| %>
        <% if comment.id.present? %>
            <li>
                <div class="comment-content" id="this_comment_<%= comment.id %>"></div>

                <p><%= comment.content %></p>

                <p><%= link_to "Edit", edit_blog_comment_path(blog, comment), remote: true %></p>

                <p><%= link_to "Delete", blog_comment_path(comment.blog_id, comment.id), method: :delete, remote: true,
                                        data: { confirm: "Are you sure to delete this??"} %></p>
            </li>
        <% end %>
    <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render'comments/edit', blog: @blog, comment: @comment %>")

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$("textarea").val('')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsConnection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <ul class="nav justify-content-end">
        <% if user_signed_in? %>
          <a class="nav-link text-dark"><%= current_user.email %></a>
          <%= link_to "Users List", users_path, class: "nav-link" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>

      <div class="col-md-6 mx-auto">
        <% if notice %>
        <div class="alert alert-warning text-centere" role="alert">
          <%= notice %>
        </div>
        <% end %>
        <% if alert %>
        <div class="alert alert-warning text-center" role="alert">
          <%= alert %>
        </div>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h2>Users</h2>
<% @users.each do |u| %>
    <%= u.name %>
    <%= u.email %>
    <%= render 'follow_form', user: user %>
<% end %>